# Form implementation generated from reading ui file 'D:\15_03_K234111402\K23_mlba\Api\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 353)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 211, 21))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 231, 31))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 231, 31))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEditText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditText.setGeometry(QtCore.QRect(290, 30, 211, 31))
        self.lineEditText.setObjectName("lineEditText")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 210, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.labelResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(180, 270, 211, 21))
        self.labelResult.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.comboBoxSource = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxSource.setGeometry(QtCore.QRect(300, 90, 91, 31))
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.comboBoxSource.addItem("")
        self.comboBoxSource.addItem("")
        self.comboBoxTarget = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxTarget.setGeometry(QtCore.QRect(300, 150, 91, 31))
        self.comboBoxTarget.setObjectName("comboBoxTarget")
        self.comboBoxTarget.addItem("")
        self.comboBoxTarget.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Translate-Thanh Ngan"))
        self.label.setText(_translate("MainWindow", "Enter text to translate:"))
        self.label_2.setText(_translate("MainWindow", "Choose source language:"))
        self.label_3.setText(_translate("MainWindow", "Choose target language:"))
        self.pushButton.setText(_translate("MainWindow", "Tranlate"))
        self.comboBoxSource.setItemText(0, _translate("MainWindow", "vi"))
        self.comboBoxSource.setItemText(1, _translate("MainWindow", "en"))
        self.comboBoxTarget.setItemText(0, _translate("MainWindow", "en"))
        self.comboBoxTarget.setItemText(1, _translate("MainWindow", "vi"))
